/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n      query receipt {\n        order {\n          ...order\n        }\n      }\n    ": typeof types.ReceiptDocument,
    "\n      mutation paymentResult($paymentMethodFields: Map!) {\n        paymentResult(paymentMethodFields: $paymentMethodFields) {\n          type\n          userErrors {\n            message\n            path\n          }\n        }\n      }\n    ": typeof types.PaymentResultDocument,
    "\n          mutation addFlexibleBundleToCart($item: String!, $sections: [BundleSectionInput!]!, $quantity: Int = 1) {\n            addFlexibleBundle(item: $item, quantity: $quantity, sections: $sections) {\n              userErrors {\n                message\n                path\n              }\n              selection {\n                ...cart\n              }\n            }\n          }\n        ": typeof types.AddFlexibleBundleToCartDocument,
    "\n          mutation addItem($item: String!, $quantity: Int = 1) {\n            addItem(item: $item, quantity: $quantity) {\n              userErrors {\n                message\n                path\n              }\n              selection {\n                ...cart\n              }\n            }\n          }\n        ": typeof types.AddItemDocument,
    "\n          mutation updateLine($id: String!, $quantity: Int!) {\n            updateLine(lineId: $id, quantity: $quantity) {\n              userErrors {\n                message\n                path\n              }\n              selection {\n                ...cart\n              }\n            }\n          }\n        ": typeof types.UpdateLineDocument,
    "\n        query cart {\n          selection {\n            ...cart\n          }\n        }\n      ": typeof types.CartDocument,
    "\n          mutation setAddress($billingAddress: AddressInput!, $shippingAddress: AddressInput!) {\n            setAddress(separateBillingAddress: $billingAddress, shippingAddress: $shippingAddress) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": typeof types.SetAddressDocument,
    "\n          mutation setShippingMethod($id: Int!) {\n            setShippingMethod(id: $id) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": typeof types.SetShippingMethodDocument,
    "\n          mutation setPaymentMethod($paymentMethod: Int!) {\n            setPaymentMethod(id: $paymentMethod) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": typeof types.SetPaymentMethodDocument,
    "\n          mutation paymentInstructions($input: PaymentInstructionsInput!) {\n            paymentInstructions(input: $input) {\n              action {\n                ...paymentAction\n              }\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n                ... on UnavailableItem {\n                  __typename\n                }\n              }\n            }\n          }\n        ": typeof types.PaymentInstructionsDocument,
    "\n          mutation widgetEvent($payload: Map!) {\n            handleWidgetEvent(payload: $payload) {\n              selection {\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": typeof types.WidgetEventDocument,
    "\n          mutation addVoucher($code: String!) {\n            addVoucher(code: $code) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": typeof types.AddVoucherDocument,
    "\n          mutation removeVoucher($code: String!) {\n            removeVoucher(code: $code) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": typeof types.RemoveVoucherDocument,
    "\n          mutation setCountryState($countryCode: String!, $stateCode: String!) {\n            setCountryState(countryCode: $countryCode, stateCode: $stateCode) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": typeof types.SetCountryStateDocument,
    "\n        query checkout {\n          selection {\n            ...checkout\n          }\n        }\n      ": typeof types.CheckoutDocument,
    "\n      query session {\n        session {\n          ...session\n        }\n      }\n    ": typeof types.SessionDocument,
    "\n      mutation setCountryAndLanguage($country: String!, $state: String, $language: String!) {\n        setCountryState(countryCode: $country, stateCode: $state) {\n          userErrors {\n            message\n            path\n          }\n        }\n        setLanguage(code: $language) {\n          session {\n            ...session\n          }\n        }\n      }\n    ": typeof types.SetCountryAndLanguageDocument,
    "\n      query orders($limit: Int!, $page: Int!) {\n        customer {\n          orders(limit: $limit, page: $page) {\n            ...order\n          }\n          totalOrders\n        }\n      }\n    ": typeof types.OrdersDocument,
    "\n        mutation login($email: String!, $password: String!) {\n          login(email: $email, password: $password) {\n            session {\n              ...session\n            }\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": typeof types.LoginDocument,
    "\n        mutation register($input: CustomerRegisterInput!) {\n          registerCustomer(input: $input) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": typeof types.RegisterDocument,
    "\n        mutation logout {\n          logout {\n            session {\n              ...session\n            }\n          }\n        }\n      ": typeof types.LogoutDocument,
    "\n        mutation forgotPassword($email: String!, $uri: String!) {\n          requestPasswordResetEmail(email: $email, resetPasswordExternalUrl: $uri) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": typeof types.ForgotPasswordDocument,
    "\n        mutation resetPassword($password: String!, $confirmPassword: String!, $i: String!, $id: String!) {\n          resetPassword(password: $password, confirmPassword: $confirmPassword, i: $i, id: $id) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": typeof types.ResetPasswordDocument,
    "\n        query productDetails($id: Int!) {\n          displayItem(id: $id) {\n            id\n            bundle {\n              type\n              priceType\n              minPriceByPricelist {\n                pricelist {\n                  id\n                }\n                priceByMarket {\n                  markets\n                  price {\n                    formattedValue\n                  }\n                }\n              }\n              maxPriceByPricelist {\n                pricelist {\n                  id\n                }\n                priceByMarket {\n                  markets\n                  price {\n                    formattedValue\n                  }\n                }\n              }\n              sections {\n                id\n                quantity\n                items {\n                  id\n                  name\n                  media {\n                    source(sizeName: \"standard\") {\n                      url\n                    }\n                  }\n                  priceByPricelist {\n                    pricelist {\n                      id\n                    }\n                    priceByMarket {\n                      markets\n                      price {\n                        formattedValue\n                        value\n                        currency {\n                          code\n                        }\n                      }\n                    }\n                  }\n                  items {\n                    ...item\n                  }\n                  translations {\n                    language {\n                      code\n                    }\n                    name\n                  }\n                }\n              }\n            }\n            media {\n              source(sizeName: \"full\") {\n                url\n              }\n            }\n            priceByPricelist {\n              pricelist {\n                id\n              }\n              priceByMarket {\n                markets\n                price {\n                  formattedValue\n                  value\n                  currency {\n                    code\n                  }\n                }\n              }\n            }\n            items {\n              ...item\n            }\n            translations {\n              language {\n                code\n              }\n              uri\n              name\n              metaTitle\n              metaDescription\n              description {\n                formatted\n              }\n            }\n          }\n        }\n      ": typeof types.ProductDetailsDocument,
    "\n        query productAvailability($id: Int!, $market: [Int!]!, $pricelist: [Int!]!) {\n          displayItem(id: $id, market: $market, pricelist: $pricelist) {\n            available\n            items {\n              id\n              stock {\n                available\n              }\n            }\n            bundle {\n              sections {\n                id\n                items {\n                  id\n                  items {\n                    id\n                    stock {\n                      available\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": typeof types.ProductAvailabilityDocument,
    "\n      query products(\n        $page: Int!\n        $search: String\n        $sort: [CustomSortInput!] = []\n        $filters: [FilterInput!] = []\n        $limit: Int = 40\n        $market: Int!\n        $pricelist: Int!\n        $language: String!\n        $withFilters: Boolean = true\n      ) {\n        displayItems(\n          limit: $limit\n          page: $page\n          where: { search: $search, filters: $filters }\n          sort: $sort\n          market: [$market]\n          pricelist: [$pricelist]\n          languageCode: [$language]\n        ) {\n          list {\n            id\n            uri\n            name\n            media {\n              source(sizeName: \"standard\") {\n                url\n              }\n            }\n            price {\n              formattedValue\n            }\n            bundle {\n              type\n              priceType\n              minPrice {\n                formattedValue\n              }\n            }\n          }\n          pagination {\n            currentPage\n            lastPage\n          }\n          filters @include(if: $withFilters) {\n            key\n            anyAvailable\n            selectedValues\n            values {\n              __typename\n              value\n              filterCount\n              ... on BrandFilterValue {\n                name\n              }\n              ... on CategoryFilterValue {\n                category {\n                  id\n                }\n              }\n            }\n          }\n        }\n      }\n    ": typeof types.ProductsDocument,
    "\n      query countriesAndLanguages {\n        countries(onlyShipTo: true) {\n          name\n          code\n          defaultLanguage {\n            code\n            languageCode\n          }\n          translations {\n            language {\n              code\n            }\n            name\n          }\n        }\n        languages {\n          languageCode\n          name\n          code\n          countryCode\n        }\n      }\n    ": typeof types.CountriesAndLanguagesDocument,
    "\n      query countries {\n        countries(onlyShipTo: true) {\n          name\n          code\n          states {\n            name\n            code\n          }\n          translations {\n            language {\n              code\n            }\n            name\n          }\n        }\n      }\n    ": typeof types.CountriesDocument,
    "\n      query categories($limit: Int!) {\n        categories(limit: $limit, parent: 0) {\n          list {\n            id\n            translations {\n              name\n              uri\n              language {\n                code\n              }\n            }\n          }\n        }\n      }\n    ": typeof types.CategoriesDocument,
    "\n        query categoryDetails($id: Int!) {\n          categories(id: [$id], limit: 1) {\n            list {\n              id\n              translations {\n                uri\n                language {\n                  code\n                }\n                name\n                metaTitle\n                metaDescription\n              }\n            }\n          }\n        }\n      ": typeof types.CategoryDetailsDocument,
    "fragment checkout on Selection {\n  discounts {\n    ...voucher\n  }\n  checkout {\n    checkoutScript\n    separateBillingAddress {\n      ...address\n    }\n    shippingAddress {\n      ...address\n    }\n    paymentMethods {\n      id\n      uri\n      name\n      kind\n      initiateOnlySupported\n      handlingCost {\n        formattedValue\n        value\n      }\n    }\n    paymentMethod {\n      id\n    }\n    shippingMethods {\n      id\n      name\n      comment\n      price {\n        formattedValue\n        value\n      }\n    }\n    shippingMethod {\n      id\n      name\n      comment\n      price {\n        value\n        formattedValue\n      }\n    }\n    totals {\n      type\n      price {\n        value\n        formattedValue\n      }\n    }\n    widgets {\n      __typename\n      ... on IngridWidget {\n        snippet\n        deliveryOptionsAvailable\n      }\n      ... on KlarnaPaymentWidget {\n        client_token\n        authorizePayload\n      }\n    }\n  }\n}\n\nfragment address on Address {\n  country {\n    code\n    name\n  }\n  state {\n    code\n    name\n  }\n  address1\n  address2\n  city\n  zipCode\n  email\n  firstName\n  lastName\n  phoneNumber\n  companyName\n  vatNumber\n}\n\nfragment order on Order {\n  id\n  number\n  orderDate\n  status\n  totals {\n    type\n    price {\n      value\n      formattedValue\n    }\n  }\n  shippingAddress {\n    ...address\n  }\n  billingAddress {\n    ...address\n  }\n  shippingMethod {\n    id\n    name\n    comment\n    selected\n    price {\n      value\n      formattedValue\n    }\n  }\n  lines {\n    ...line\n  }\n}\n\nfragment voucher on Voucher {\n  name\n  value {\n    value\n    formattedValue\n  }\n  ... on CodeVoucher {\n    code\n  }\n}\n\nfragment paymentAction on PaymentAction {\n  __typename\n  ... on FormPaymentAction {\n    html\n    formFields\n    formType\n  }\n  ... on RedirectPaymentAction {\n    url\n  }\n  ... on JavascriptPaymentAction {\n    script\n    formFields\n  }\n  ... on SuccessPaymentAction {\n    order {\n      id\n    }\n  }\n}": typeof types.CheckoutFragmentDoc,
    "fragment item on Item {\n  id\n  name\n  sizeLocalization {\n    name\n    countries {\n      code\n    }\n  }\n}": typeof types.ItemFragmentDoc,
    "fragment cart on Selection {\n  lines {\n    ...line\n  }\n  grandTotal {\n    value\n    currency {\n      denominator\n      code\n      prefix\n      suffix\n    }\n  }\n}\n\nfragment line on Line {\n  __typename\n  id\n  item {\n    ...item\n  }\n  quantity\n  lineValue {\n    formattedValue\n    value\n  }\n  displayItem {\n    id\n    name\n    uri\n    media {\n      source(sizeName: \"mini\") {\n        url\n      }\n    }\n  }\n  ... on BundleLine {\n    bundle {\n      type\n      sections {\n        quantity\n        lines {\n          id\n          lineValue {\n            formattedValue\n          }\n          name\n          quantity\n          item {\n            ...item\n          }\n        }\n      }\n    }\n  }\n}": typeof types.CartFragmentDoc,
    "fragment session on Session {\n  country {\n    code\n  }\n  countryState {\n    code\n  }\n  language {\n    code\n  }\n  market {\n    id\n  }\n  pricelist {\n    id\n  }\n  loggedIn {\n    id\n  }\n}": typeof types.SessionFragmentDoc,
};
const documents: Documents = {
    "\n      query receipt {\n        order {\n          ...order\n        }\n      }\n    ": types.ReceiptDocument,
    "\n      mutation paymentResult($paymentMethodFields: Map!) {\n        paymentResult(paymentMethodFields: $paymentMethodFields) {\n          type\n          userErrors {\n            message\n            path\n          }\n        }\n      }\n    ": types.PaymentResultDocument,
    "\n          mutation addFlexibleBundleToCart($item: String!, $sections: [BundleSectionInput!]!, $quantity: Int = 1) {\n            addFlexibleBundle(item: $item, quantity: $quantity, sections: $sections) {\n              userErrors {\n                message\n                path\n              }\n              selection {\n                ...cart\n              }\n            }\n          }\n        ": types.AddFlexibleBundleToCartDocument,
    "\n          mutation addItem($item: String!, $quantity: Int = 1) {\n            addItem(item: $item, quantity: $quantity) {\n              userErrors {\n                message\n                path\n              }\n              selection {\n                ...cart\n              }\n            }\n          }\n        ": types.AddItemDocument,
    "\n          mutation updateLine($id: String!, $quantity: Int!) {\n            updateLine(lineId: $id, quantity: $quantity) {\n              userErrors {\n                message\n                path\n              }\n              selection {\n                ...cart\n              }\n            }\n          }\n        ": types.UpdateLineDocument,
    "\n        query cart {\n          selection {\n            ...cart\n          }\n        }\n      ": types.CartDocument,
    "\n          mutation setAddress($billingAddress: AddressInput!, $shippingAddress: AddressInput!) {\n            setAddress(separateBillingAddress: $billingAddress, shippingAddress: $shippingAddress) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": types.SetAddressDocument,
    "\n          mutation setShippingMethod($id: Int!) {\n            setShippingMethod(id: $id) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": types.SetShippingMethodDocument,
    "\n          mutation setPaymentMethod($paymentMethod: Int!) {\n            setPaymentMethod(id: $paymentMethod) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": types.SetPaymentMethodDocument,
    "\n          mutation paymentInstructions($input: PaymentInstructionsInput!) {\n            paymentInstructions(input: $input) {\n              action {\n                ...paymentAction\n              }\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n                ... on UnavailableItem {\n                  __typename\n                }\n              }\n            }\n          }\n        ": types.PaymentInstructionsDocument,
    "\n          mutation widgetEvent($payload: Map!) {\n            handleWidgetEvent(payload: $payload) {\n              selection {\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": types.WidgetEventDocument,
    "\n          mutation addVoucher($code: String!) {\n            addVoucher(code: $code) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": types.AddVoucherDocument,
    "\n          mutation removeVoucher($code: String!) {\n            removeVoucher(code: $code) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": types.RemoveVoucherDocument,
    "\n          mutation setCountryState($countryCode: String!, $stateCode: String!) {\n            setCountryState(countryCode: $countryCode, stateCode: $stateCode) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        ": types.SetCountryStateDocument,
    "\n        query checkout {\n          selection {\n            ...checkout\n          }\n        }\n      ": types.CheckoutDocument,
    "\n      query session {\n        session {\n          ...session\n        }\n      }\n    ": types.SessionDocument,
    "\n      mutation setCountryAndLanguage($country: String!, $state: String, $language: String!) {\n        setCountryState(countryCode: $country, stateCode: $state) {\n          userErrors {\n            message\n            path\n          }\n        }\n        setLanguage(code: $language) {\n          session {\n            ...session\n          }\n        }\n      }\n    ": types.SetCountryAndLanguageDocument,
    "\n      query orders($limit: Int!, $page: Int!) {\n        customer {\n          orders(limit: $limit, page: $page) {\n            ...order\n          }\n          totalOrders\n        }\n      }\n    ": types.OrdersDocument,
    "\n        mutation login($email: String!, $password: String!) {\n          login(email: $email, password: $password) {\n            session {\n              ...session\n            }\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": types.LoginDocument,
    "\n        mutation register($input: CustomerRegisterInput!) {\n          registerCustomer(input: $input) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": types.RegisterDocument,
    "\n        mutation logout {\n          logout {\n            session {\n              ...session\n            }\n          }\n        }\n      ": types.LogoutDocument,
    "\n        mutation forgotPassword($email: String!, $uri: String!) {\n          requestPasswordResetEmail(email: $email, resetPasswordExternalUrl: $uri) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": types.ForgotPasswordDocument,
    "\n        mutation resetPassword($password: String!, $confirmPassword: String!, $i: String!, $id: String!) {\n          resetPassword(password: $password, confirmPassword: $confirmPassword, i: $i, id: $id) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": types.ResetPasswordDocument,
    "\n        query productDetails($id: Int!) {\n          displayItem(id: $id) {\n            id\n            bundle {\n              type\n              priceType\n              minPriceByPricelist {\n                pricelist {\n                  id\n                }\n                priceByMarket {\n                  markets\n                  price {\n                    formattedValue\n                  }\n                }\n              }\n              maxPriceByPricelist {\n                pricelist {\n                  id\n                }\n                priceByMarket {\n                  markets\n                  price {\n                    formattedValue\n                  }\n                }\n              }\n              sections {\n                id\n                quantity\n                items {\n                  id\n                  name\n                  media {\n                    source(sizeName: \"standard\") {\n                      url\n                    }\n                  }\n                  priceByPricelist {\n                    pricelist {\n                      id\n                    }\n                    priceByMarket {\n                      markets\n                      price {\n                        formattedValue\n                        value\n                        currency {\n                          code\n                        }\n                      }\n                    }\n                  }\n                  items {\n                    ...item\n                  }\n                  translations {\n                    language {\n                      code\n                    }\n                    name\n                  }\n                }\n              }\n            }\n            media {\n              source(sizeName: \"full\") {\n                url\n              }\n            }\n            priceByPricelist {\n              pricelist {\n                id\n              }\n              priceByMarket {\n                markets\n                price {\n                  formattedValue\n                  value\n                  currency {\n                    code\n                  }\n                }\n              }\n            }\n            items {\n              ...item\n            }\n            translations {\n              language {\n                code\n              }\n              uri\n              name\n              metaTitle\n              metaDescription\n              description {\n                formatted\n              }\n            }\n          }\n        }\n      ": types.ProductDetailsDocument,
    "\n        query productAvailability($id: Int!, $market: [Int!]!, $pricelist: [Int!]!) {\n          displayItem(id: $id, market: $market, pricelist: $pricelist) {\n            available\n            items {\n              id\n              stock {\n                available\n              }\n            }\n            bundle {\n              sections {\n                id\n                items {\n                  id\n                  items {\n                    id\n                    stock {\n                      available\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": types.ProductAvailabilityDocument,
    "\n      query products(\n        $page: Int!\n        $search: String\n        $sort: [CustomSortInput!] = []\n        $filters: [FilterInput!] = []\n        $limit: Int = 40\n        $market: Int!\n        $pricelist: Int!\n        $language: String!\n        $withFilters: Boolean = true\n      ) {\n        displayItems(\n          limit: $limit\n          page: $page\n          where: { search: $search, filters: $filters }\n          sort: $sort\n          market: [$market]\n          pricelist: [$pricelist]\n          languageCode: [$language]\n        ) {\n          list {\n            id\n            uri\n            name\n            media {\n              source(sizeName: \"standard\") {\n                url\n              }\n            }\n            price {\n              formattedValue\n            }\n            bundle {\n              type\n              priceType\n              minPrice {\n                formattedValue\n              }\n            }\n          }\n          pagination {\n            currentPage\n            lastPage\n          }\n          filters @include(if: $withFilters) {\n            key\n            anyAvailable\n            selectedValues\n            values {\n              __typename\n              value\n              filterCount\n              ... on BrandFilterValue {\n                name\n              }\n              ... on CategoryFilterValue {\n                category {\n                  id\n                }\n              }\n            }\n          }\n        }\n      }\n    ": types.ProductsDocument,
    "\n      query countriesAndLanguages {\n        countries(onlyShipTo: true) {\n          name\n          code\n          defaultLanguage {\n            code\n            languageCode\n          }\n          translations {\n            language {\n              code\n            }\n            name\n          }\n        }\n        languages {\n          languageCode\n          name\n          code\n          countryCode\n        }\n      }\n    ": types.CountriesAndLanguagesDocument,
    "\n      query countries {\n        countries(onlyShipTo: true) {\n          name\n          code\n          states {\n            name\n            code\n          }\n          translations {\n            language {\n              code\n            }\n            name\n          }\n        }\n      }\n    ": types.CountriesDocument,
    "\n      query categories($limit: Int!) {\n        categories(limit: $limit, parent: 0) {\n          list {\n            id\n            translations {\n              name\n              uri\n              language {\n                code\n              }\n            }\n          }\n        }\n      }\n    ": types.CategoriesDocument,
    "\n        query categoryDetails($id: Int!) {\n          categories(id: [$id], limit: 1) {\n            list {\n              id\n              translations {\n                uri\n                language {\n                  code\n                }\n                name\n                metaTitle\n                metaDescription\n              }\n            }\n          }\n        }\n      ": types.CategoryDetailsDocument,
    "fragment checkout on Selection {\n  discounts {\n    ...voucher\n  }\n  checkout {\n    checkoutScript\n    separateBillingAddress {\n      ...address\n    }\n    shippingAddress {\n      ...address\n    }\n    paymentMethods {\n      id\n      uri\n      name\n      kind\n      initiateOnlySupported\n      handlingCost {\n        formattedValue\n        value\n      }\n    }\n    paymentMethod {\n      id\n    }\n    shippingMethods {\n      id\n      name\n      comment\n      price {\n        formattedValue\n        value\n      }\n    }\n    shippingMethod {\n      id\n      name\n      comment\n      price {\n        value\n        formattedValue\n      }\n    }\n    totals {\n      type\n      price {\n        value\n        formattedValue\n      }\n    }\n    widgets {\n      __typename\n      ... on IngridWidget {\n        snippet\n        deliveryOptionsAvailable\n      }\n      ... on KlarnaPaymentWidget {\n        client_token\n        authorizePayload\n      }\n    }\n  }\n}\n\nfragment address on Address {\n  country {\n    code\n    name\n  }\n  state {\n    code\n    name\n  }\n  address1\n  address2\n  city\n  zipCode\n  email\n  firstName\n  lastName\n  phoneNumber\n  companyName\n  vatNumber\n}\n\nfragment order on Order {\n  id\n  number\n  orderDate\n  status\n  totals {\n    type\n    price {\n      value\n      formattedValue\n    }\n  }\n  shippingAddress {\n    ...address\n  }\n  billingAddress {\n    ...address\n  }\n  shippingMethod {\n    id\n    name\n    comment\n    selected\n    price {\n      value\n      formattedValue\n    }\n  }\n  lines {\n    ...line\n  }\n}\n\nfragment voucher on Voucher {\n  name\n  value {\n    value\n    formattedValue\n  }\n  ... on CodeVoucher {\n    code\n  }\n}\n\nfragment paymentAction on PaymentAction {\n  __typename\n  ... on FormPaymentAction {\n    html\n    formFields\n    formType\n  }\n  ... on RedirectPaymentAction {\n    url\n  }\n  ... on JavascriptPaymentAction {\n    script\n    formFields\n  }\n  ... on SuccessPaymentAction {\n    order {\n      id\n    }\n  }\n}": types.CheckoutFragmentDoc,
    "fragment item on Item {\n  id\n  name\n  sizeLocalization {\n    name\n    countries {\n      code\n    }\n  }\n}": types.ItemFragmentDoc,
    "fragment cart on Selection {\n  lines {\n    ...line\n  }\n  grandTotal {\n    value\n    currency {\n      denominator\n      code\n      prefix\n      suffix\n    }\n  }\n}\n\nfragment line on Line {\n  __typename\n  id\n  item {\n    ...item\n  }\n  quantity\n  lineValue {\n    formattedValue\n    value\n  }\n  displayItem {\n    id\n    name\n    uri\n    media {\n      source(sizeName: \"mini\") {\n        url\n      }\n    }\n  }\n  ... on BundleLine {\n    bundle {\n      type\n      sections {\n        quantity\n        lines {\n          id\n          lineValue {\n            formattedValue\n          }\n          name\n          quantity\n          item {\n            ...item\n          }\n        }\n      }\n    }\n  }\n}": types.CartFragmentDoc,
    "fragment session on Session {\n  country {\n    code\n  }\n  countryState {\n    code\n  }\n  language {\n    code\n  }\n  market {\n    id\n  }\n  pricelist {\n    id\n  }\n  loggedIn {\n    id\n  }\n}": types.SessionFragmentDoc,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query receipt {\n        order {\n          ...order\n        }\n      }\n    "): typeof import('./graphql').ReceiptDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      mutation paymentResult($paymentMethodFields: Map!) {\n        paymentResult(paymentMethodFields: $paymentMethodFields) {\n          type\n          userErrors {\n            message\n            path\n          }\n        }\n      }\n    "): typeof import('./graphql').PaymentResultDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation addFlexibleBundleToCart($item: String!, $sections: [BundleSectionInput!]!, $quantity: Int = 1) {\n            addFlexibleBundle(item: $item, quantity: $quantity, sections: $sections) {\n              userErrors {\n                message\n                path\n              }\n              selection {\n                ...cart\n              }\n            }\n          }\n        "): typeof import('./graphql').AddFlexibleBundleToCartDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation addItem($item: String!, $quantity: Int = 1) {\n            addItem(item: $item, quantity: $quantity) {\n              userErrors {\n                message\n                path\n              }\n              selection {\n                ...cart\n              }\n            }\n          }\n        "): typeof import('./graphql').AddItemDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation updateLine($id: String!, $quantity: Int!) {\n            updateLine(lineId: $id, quantity: $quantity) {\n              userErrors {\n                message\n                path\n              }\n              selection {\n                ...cart\n              }\n            }\n          }\n        "): typeof import('./graphql').UpdateLineDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query cart {\n          selection {\n            ...cart\n          }\n        }\n      "): typeof import('./graphql').CartDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation setAddress($billingAddress: AddressInput!, $shippingAddress: AddressInput!) {\n            setAddress(separateBillingAddress: $billingAddress, shippingAddress: $shippingAddress) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        "): typeof import('./graphql').SetAddressDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation setShippingMethod($id: Int!) {\n            setShippingMethod(id: $id) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        "): typeof import('./graphql').SetShippingMethodDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation setPaymentMethod($paymentMethod: Int!) {\n            setPaymentMethod(id: $paymentMethod) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        "): typeof import('./graphql').SetPaymentMethodDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation paymentInstructions($input: PaymentInstructionsInput!) {\n            paymentInstructions(input: $input) {\n              action {\n                ...paymentAction\n              }\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n                ... on UnavailableItem {\n                  __typename\n                }\n              }\n            }\n          }\n        "): typeof import('./graphql').PaymentInstructionsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation widgetEvent($payload: Map!) {\n            handleWidgetEvent(payload: $payload) {\n              selection {\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        "): typeof import('./graphql').WidgetEventDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation addVoucher($code: String!) {\n            addVoucher(code: $code) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        "): typeof import('./graphql').AddVoucherDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation removeVoucher($code: String!) {\n            removeVoucher(code: $code) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        "): typeof import('./graphql').RemoveVoucherDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n          mutation setCountryState($countryCode: String!, $stateCode: String!) {\n            setCountryState(countryCode: $countryCode, stateCode: $stateCode) {\n              selection {\n                ...cart\n                ...checkout\n              }\n              userErrors {\n                message\n                path\n              }\n            }\n          }\n        "): typeof import('./graphql').SetCountryStateDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query checkout {\n          selection {\n            ...checkout\n          }\n        }\n      "): typeof import('./graphql').CheckoutDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query session {\n        session {\n          ...session\n        }\n      }\n    "): typeof import('./graphql').SessionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      mutation setCountryAndLanguage($country: String!, $state: String, $language: String!) {\n        setCountryState(countryCode: $country, stateCode: $state) {\n          userErrors {\n            message\n            path\n          }\n        }\n        setLanguage(code: $language) {\n          session {\n            ...session\n          }\n        }\n      }\n    "): typeof import('./graphql').SetCountryAndLanguageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query orders($limit: Int!, $page: Int!) {\n        customer {\n          orders(limit: $limit, page: $page) {\n            ...order\n          }\n          totalOrders\n        }\n      }\n    "): typeof import('./graphql').OrdersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation login($email: String!, $password: String!) {\n          login(email: $email, password: $password) {\n            session {\n              ...session\n            }\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      "): typeof import('./graphql').LoginDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation register($input: CustomerRegisterInput!) {\n          registerCustomer(input: $input) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      "): typeof import('./graphql').RegisterDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation logout {\n          logout {\n            session {\n              ...session\n            }\n          }\n        }\n      "): typeof import('./graphql').LogoutDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation forgotPassword($email: String!, $uri: String!) {\n          requestPasswordResetEmail(email: $email, resetPasswordExternalUrl: $uri) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      "): typeof import('./graphql').ForgotPasswordDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation resetPassword($password: String!, $confirmPassword: String!, $i: String!, $id: String!) {\n          resetPassword(password: $password, confirmPassword: $confirmPassword, i: $i, id: $id) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      "): typeof import('./graphql').ResetPasswordDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query productDetails($id: Int!) {\n          displayItem(id: $id) {\n            id\n            bundle {\n              type\n              priceType\n              minPriceByPricelist {\n                pricelist {\n                  id\n                }\n                priceByMarket {\n                  markets\n                  price {\n                    formattedValue\n                  }\n                }\n              }\n              maxPriceByPricelist {\n                pricelist {\n                  id\n                }\n                priceByMarket {\n                  markets\n                  price {\n                    formattedValue\n                  }\n                }\n              }\n              sections {\n                id\n                quantity\n                items {\n                  id\n                  name\n                  media {\n                    source(sizeName: \"standard\") {\n                      url\n                    }\n                  }\n                  priceByPricelist {\n                    pricelist {\n                      id\n                    }\n                    priceByMarket {\n                      markets\n                      price {\n                        formattedValue\n                        value\n                        currency {\n                          code\n                        }\n                      }\n                    }\n                  }\n                  items {\n                    ...item\n                  }\n                  translations {\n                    language {\n                      code\n                    }\n                    name\n                  }\n                }\n              }\n            }\n            media {\n              source(sizeName: \"full\") {\n                url\n              }\n            }\n            priceByPricelist {\n              pricelist {\n                id\n              }\n              priceByMarket {\n                markets\n                price {\n                  formattedValue\n                  value\n                  currency {\n                    code\n                  }\n                }\n              }\n            }\n            items {\n              ...item\n            }\n            translations {\n              language {\n                code\n              }\n              uri\n              name\n              metaTitle\n              metaDescription\n              description {\n                formatted\n              }\n            }\n          }\n        }\n      "): typeof import('./graphql').ProductDetailsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query productAvailability($id: Int!, $market: [Int!]!, $pricelist: [Int!]!) {\n          displayItem(id: $id, market: $market, pricelist: $pricelist) {\n            available\n            items {\n              id\n              stock {\n                available\n              }\n            }\n            bundle {\n              sections {\n                id\n                items {\n                  id\n                  items {\n                    id\n                    stock {\n                      available\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      "): typeof import('./graphql').ProductAvailabilityDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query products(\n        $page: Int!\n        $search: String\n        $sort: [CustomSortInput!] = []\n        $filters: [FilterInput!] = []\n        $limit: Int = 40\n        $market: Int!\n        $pricelist: Int!\n        $language: String!\n        $withFilters: Boolean = true\n      ) {\n        displayItems(\n          limit: $limit\n          page: $page\n          where: { search: $search, filters: $filters }\n          sort: $sort\n          market: [$market]\n          pricelist: [$pricelist]\n          languageCode: [$language]\n        ) {\n          list {\n            id\n            uri\n            name\n            media {\n              source(sizeName: \"standard\") {\n                url\n              }\n            }\n            price {\n              formattedValue\n            }\n            bundle {\n              type\n              priceType\n              minPrice {\n                formattedValue\n              }\n            }\n          }\n          pagination {\n            currentPage\n            lastPage\n          }\n          filters @include(if: $withFilters) {\n            key\n            anyAvailable\n            selectedValues\n            values {\n              __typename\n              value\n              filterCount\n              ... on BrandFilterValue {\n                name\n              }\n              ... on CategoryFilterValue {\n                category {\n                  id\n                }\n              }\n            }\n          }\n        }\n      }\n    "): typeof import('./graphql').ProductsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query countriesAndLanguages {\n        countries(onlyShipTo: true) {\n          name\n          code\n          defaultLanguage {\n            code\n            languageCode\n          }\n          translations {\n            language {\n              code\n            }\n            name\n          }\n        }\n        languages {\n          languageCode\n          name\n          code\n          countryCode\n        }\n      }\n    "): typeof import('./graphql').CountriesAndLanguagesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query countries {\n        countries(onlyShipTo: true) {\n          name\n          code\n          states {\n            name\n            code\n          }\n          translations {\n            language {\n              code\n            }\n            name\n          }\n        }\n      }\n    "): typeof import('./graphql').CountriesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query categories($limit: Int!) {\n        categories(limit: $limit, parent: 0) {\n          list {\n            id\n            translations {\n              name\n              uri\n              language {\n                code\n              }\n            }\n          }\n        }\n      }\n    "): typeof import('./graphql').CategoriesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query categoryDetails($id: Int!) {\n          categories(id: [$id], limit: 1) {\n            list {\n              id\n              translations {\n                uri\n                language {\n                  code\n                }\n                name\n                metaTitle\n                metaDescription\n              }\n            }\n          }\n        }\n      "): typeof import('./graphql').CategoryDetailsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment checkout on Selection {\n  discounts {\n    ...voucher\n  }\n  checkout {\n    checkoutScript\n    separateBillingAddress {\n      ...address\n    }\n    shippingAddress {\n      ...address\n    }\n    paymentMethods {\n      id\n      uri\n      name\n      kind\n      initiateOnlySupported\n      handlingCost {\n        formattedValue\n        value\n      }\n    }\n    paymentMethod {\n      id\n    }\n    shippingMethods {\n      id\n      name\n      comment\n      price {\n        formattedValue\n        value\n      }\n    }\n    shippingMethod {\n      id\n      name\n      comment\n      price {\n        value\n        formattedValue\n      }\n    }\n    totals {\n      type\n      price {\n        value\n        formattedValue\n      }\n    }\n    widgets {\n      __typename\n      ... on IngridWidget {\n        snippet\n        deliveryOptionsAvailable\n      }\n      ... on KlarnaPaymentWidget {\n        client_token\n        authorizePayload\n      }\n    }\n  }\n}\n\nfragment address on Address {\n  country {\n    code\n    name\n  }\n  state {\n    code\n    name\n  }\n  address1\n  address2\n  city\n  zipCode\n  email\n  firstName\n  lastName\n  phoneNumber\n  companyName\n  vatNumber\n}\n\nfragment order on Order {\n  id\n  number\n  orderDate\n  status\n  totals {\n    type\n    price {\n      value\n      formattedValue\n    }\n  }\n  shippingAddress {\n    ...address\n  }\n  billingAddress {\n    ...address\n  }\n  shippingMethod {\n    id\n    name\n    comment\n    selected\n    price {\n      value\n      formattedValue\n    }\n  }\n  lines {\n    ...line\n  }\n}\n\nfragment voucher on Voucher {\n  name\n  value {\n    value\n    formattedValue\n  }\n  ... on CodeVoucher {\n    code\n  }\n}\n\nfragment paymentAction on PaymentAction {\n  __typename\n  ... on FormPaymentAction {\n    html\n    formFields\n    formType\n  }\n  ... on RedirectPaymentAction {\n    url\n  }\n  ... on JavascriptPaymentAction {\n    script\n    formFields\n  }\n  ... on SuccessPaymentAction {\n    order {\n      id\n    }\n  }\n}"): typeof import('./graphql').CheckoutFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment item on Item {\n  id\n  name\n  sizeLocalization {\n    name\n    countries {\n      code\n    }\n  }\n}"): typeof import('./graphql').ItemFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment cart on Selection {\n  lines {\n    ...line\n  }\n  grandTotal {\n    value\n    currency {\n      denominator\n      code\n      prefix\n      suffix\n    }\n  }\n}\n\nfragment line on Line {\n  __typename\n  id\n  item {\n    ...item\n  }\n  quantity\n  lineValue {\n    formattedValue\n    value\n  }\n  displayItem {\n    id\n    name\n    uri\n    media {\n      source(sizeName: \"mini\") {\n        url\n      }\n    }\n  }\n  ... on BundleLine {\n    bundle {\n      type\n      sections {\n        quantity\n        lines {\n          id\n          lineValue {\n            formattedValue\n          }\n          name\n          quantity\n          item {\n            ...item\n          }\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').CartFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment session on Session {\n  country {\n    code\n  }\n  countryState {\n    code\n  }\n  language {\n    code\n  }\n  market {\n    id\n  }\n  pricelist {\n    id\n  }\n  loggedIn {\n    id\n  }\n}"): typeof import('./graphql').SessionFragmentDoc;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
