/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n      query receipt {\n        order {\n          ...order\n        }\n      }\n    ": typeof types.ReceiptDocument,
    "\n      mutation paymentResult($paymentMethodFields: Map!) {\n        paymentResult(paymentMethodFields: $paymentMethodFields) {\n          type\n          userErrors {\n            message\n            path\n          }\n        }\n      }\n    ": typeof types.PaymentResultDocument,
    "\n        mutation changeLocale($country: String!, $language: String!) {\n          setCountryState(countryCode: $country) {\n            userErrors {\n              __typename\n              message\n              path\n            }\n          }\n          setLanguage(code: $language) {\n            session {\n              ...session\n            }\n          }\n        }\n      ": typeof types.ChangeLocaleDocument,
    "\n            mutation addFlexibleBundleToCart($item: String!, $sections: [BundleSectionInput!]!, $quantity: Int = 1) {\n              addFlexibleBundle(item: $item, quantity: $quantity, sections: $sections) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...cart\n                }\n              }\n            }\n          ": typeof types.AddFlexibleBundleToCartDocument,
    "\n            mutation addItem($item: String!, $quantity: Int = 1) {\n              addItem(item: $item, quantity: $quantity) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...cart\n                }\n              }\n            }\n          ": typeof types.AddItemDocument,
    "\n            mutation updateLine($id: String!, $quantity: Int!) {\n              updateLine(lineId: $id, quantity: $quantity) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...cart\n                }\n              }\n            }\n          ": typeof types.UpdateLineDocument,
    "\n        query cart {\n          selection {\n            ...cart\n          }\n        }\n      ": typeof types.CartDocument,
    "\n            mutation setAddress($billingAddress: AddressInput!, $shippingAddress: AddressInput!) {\n              setAddress(separateBillingAddress: $billingAddress, shippingAddress: $shippingAddress) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  __typename\n                  message\n                  path\n                }\n              }\n            }\n          ": typeof types.SetAddressDocument,
    "\n            mutation setShippingMethod($id: Int!) {\n              setShippingMethod(id: $id) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": typeof types.SetShippingMethodDocument,
    "\n            mutation setPaymentMethod($paymentMethod: Int!) {\n              setPaymentMethod(id: $paymentMethod) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": typeof types.SetPaymentMethodDocument,
    "\n            mutation paymentInstructions($input: PaymentInstructionsInput!) {\n              paymentInstructions(input: $input) {\n                action {\n                  ...paymentAction\n                }\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  __typename\n                  message\n                  path\n                }\n              }\n            }\n          ": typeof types.PaymentInstructionsDocument,
    "\n            mutation widgetEvent($payload: Map!) {\n              handleWidgetEvent(payload: $payload) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": typeof types.WidgetEventDocument,
    "\n            mutation addVoucher($code: String!) {\n              addVoucher(code: $code) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": typeof types.AddVoucherDocument,
    "\n            mutation removeVoucher($code: String!) {\n              removeVoucher(code: $code) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": typeof types.RemoveVoucherDocument,
    "\n            mutation setCountryState($countryCode: String!, $stateCode: String!) {\n              setCountryState(countryCode: $countryCode, stateCode: $stateCode) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  __typename\n                  message\n                  path\n                }\n              }\n            }\n          ": typeof types.SetCountryStateDocument,
    "\n            mutation updateLineCheckout($id: String!, $quantity: Int!) {\n              updateLine(lineId: $id, quantity: $quantity) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...checkout\n                }\n              }\n            }\n          ": typeof types.UpdateLineCheckoutDocument,
    "\n            mutation applyGiftCard($cardNumber: String!, $pin: String) {\n              applyGiftCard(input: { cardNumber: $cardNumber, pin: $pin }) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": typeof types.ApplyGiftCardDocument,
    "\n        query checkout {\n          selection {\n            ...checkout\n          }\n        }\n      ": typeof types.CheckoutDocument,
    "\n      query session {\n        session {\n          ...session\n        }\n      }\n    ": typeof types.SessionDocument,
    "\n      mutation setCountryAndLanguage($country: String!, $state: String, $language: String!) {\n        setCountryState(countryCode: $country, stateCode: $state) {\n          userErrors {\n            __typename\n            message\n            path\n          }\n        }\n        setLanguage(code: $language) {\n          session {\n            ...session\n          }\n        }\n      }\n    ": typeof types.SetCountryAndLanguageDocument,
    "\n      query orders($limit: Int!, $page: Int!) {\n        customer {\n          orders(limit: $limit, page: $page) {\n            ...order\n          }\n          totalOrders\n        }\n      }\n    ": typeof types.OrdersDocument,
    "\n      query relatedProducts($id: Int!, $language: String!, $market: Int!, $pricelist: Int!) {\n        displayItem(id: $id, languageCode: [$language], market: [$market], pricelist: [$pricelist]) {\n          relatedDisplayItems(relationType: \"standard\") {\n            relation\n            displayItems {\n              ...listProduct\n            }\n          }\n        }\n      }\n    ": typeof types.RelatedProductsDocument,
    "\n        mutation login($email: String!, $password: String!) {\n          login(email: $email, password: $password) {\n            session {\n              ...session\n            }\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": typeof types.LoginDocument,
    "\n        mutation register($input: CustomerRegisterInput!) {\n          registerCustomer(input: $input) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": typeof types.RegisterDocument,
    "\n        mutation logout {\n          logout {\n            session {\n              ...session\n            }\n          }\n        }\n      ": typeof types.LogoutDocument,
    "\n        mutation forgotPassword($email: String!, $uri: String!) {\n          requestPasswordResetEmail(email: $email, resetPasswordExternalUrl: $uri) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": typeof types.ForgotPasswordDocument,
    "\n        mutation resetPassword($password: String!, $confirmPassword: String!, $i: String!, $id: String!) {\n          resetPassword(password: $password, confirmPassword: $confirmPassword, i: $i, id: $id) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": typeof types.ResetPasswordDocument,
    "\n      mutation lookupProduct($uri: String!, $language: String!, $market: Int!, $pricelist: Int!) {\n        lookupUri(\n          uri: $uri\n          for: [DISPLAY_ITEM]\n          languageCode: [$language]\n          market: [$market]\n          pricelist: [$pricelist]\n        ) {\n          __typename\n          ... on DisplayItemUriLookupPayload {\n            displayItem {\n              id\n              available\n              uri\n              name\n              metaTitle\n              metaDescription\n              description {\n                formatted\n              }\n              media {\n                id\n                altText\n                source(sizeName: \"1350x0\") {\n                  url\n                }\n              }\n              price {\n                formattedValue\n                value\n                currency {\n                  code\n                }\n              }\n              items {\n                ...item\n                stock {\n                  available\n                  quantity\n                }\n              }\n              relatedDisplayItems(relationType: \"variant\") {\n                relation\n                displayItems {\n                  uri\n                  productVariant {\n                    name\n                  }\n                  ...variantSwatch\n                }\n              }\n              productVariant {\n                name\n              }\n              ...variantSwatch\n              translations {\n                language {\n                  code\n                }\n                uri\n              }\n              bundle {\n                ...bundle\n              }\n            }\n          }\n        }\n      }\n    ": typeof types.LookupProductDocument,
    "\n      query products(\n        $page: Int!\n        $search: String\n        $sort: [CustomSortInput!] = []\n        $filters: [FilterInput!] = []\n        $limit: Int = 40\n        $market: Int!\n        $pricelist: Int!\n        $language: String!\n        $withFilters: Boolean = true\n      ) {\n        displayItems(\n          limit: $limit\n          page: $page\n          where: { search: $search, filters: $filters }\n          sort: $sort\n          market: [$market]\n          pricelist: [$pricelist]\n          languageCode: [$language]\n        ) {\n          list {\n            ...listProduct\n          }\n          pagination {\n            currentPage\n            lastPage\n          }\n          filters @include(if: $withFilters) {\n            key\n            anyAvailable\n            selectedValues\n            values {\n              __typename\n              value\n              filterCount\n              ... on BrandFilterValue {\n                name\n              }\n            }\n          }\n        }\n      }\n    ": typeof types.ProductsDocument,
    "\n      query countries {\n        countries(onlyShipTo: true) {\n          name\n          code\n          states {\n            name\n            code\n          }\n          defaultLanguage {\n            code\n            languageCode\n          }\n          translations {\n            language {\n              code\n            }\n            name\n          }\n        }\n      }\n    ": typeof types.CountriesDocument,
    "\n      query languages {\n        languages {\n          languageCode\n          name\n          code\n          countryCode\n        }\n      }\n    ": typeof types.LanguagesDocument,
    "\n      query categories($limit: Int!, $language: String!, $market: Int!) {\n        categories(limit: $limit, parent: 0, languageCode: [$language], market: [$market]) {\n          list {\n            name\n            uri\n          }\n        }\n      }\n    ": typeof types.CategoriesDocument,
    "\n      mutation lookupCategory($uri: String!, $language: String!, $market: Int!) {\n        lookupUri(uri: $uri, for: [CATEGORY], languageCode: [$language], market: [$market]) {\n          __typename\n          ... on CategoryUriLookupPayload {\n            category {\n              id\n              uri\n              name\n              metaTitle\n              metaDescription\n              childCategories {\n                name\n                uri\n              }\n              translations {\n                uri\n                language {\n                  code\n                }\n              }\n            }\n          }\n        }\n      }\n    ": typeof types.LookupCategoryDocument,
    "fragment checkout on Selection {\n  lines {\n    ...line\n  }\n  grandTotal {\n    value\n    currency {\n      denominator\n      code\n    }\n  }\n  discounts {\n    ...voucher\n  }\n  externalGiftCardAvailable\n  checkout {\n    checkoutScript\n    separateBillingAddress {\n      ...address\n    }\n    shippingAddress {\n      ...address\n    }\n    paymentMethods {\n      id\n      uri\n      name\n      kind\n      initiateOnlySupported\n      handlingCost {\n        formattedValue\n        value\n      }\n    }\n    paymentMethod {\n      id\n    }\n    shippingMethods {\n      id\n      name\n      comment\n      price {\n        formattedValue\n        value\n      }\n    }\n    shippingMethod {\n      id\n      name\n      comment\n      price {\n        value\n        formattedValue\n      }\n    }\n    totals {\n      type\n      price {\n        value\n        formattedValue\n      }\n    }\n    widgets {\n      __typename\n      ... on IngridWidget {\n        snippet\n        deliveryOptionsAvailable\n      }\n      ... on KlarnaPaymentWidget {\n        client_token\n        authorizePayload\n      }\n    }\n  }\n}\n\nfragment address on Address {\n  country {\n    code\n    name\n  }\n  state {\n    code\n    name\n  }\n  address1\n  address2\n  city\n  zipCode\n  email\n  firstName\n  lastName\n  phoneNumber\n  companyName\n  vatNumber\n}\n\nfragment order on Order {\n  id\n  number\n  orderDate\n  status\n  totals {\n    type\n    price {\n      value\n      formattedValue\n    }\n  }\n  shippingAddress {\n    ...address\n  }\n  billingAddress {\n    ...address\n  }\n  shippingMethod {\n    id\n    name\n    comment\n    selected\n    price {\n      value\n      formattedValue\n    }\n  }\n  lines {\n    ...line\n  }\n}\n\nfragment voucher on Voucher {\n  name\n  value {\n    value\n    formattedValue\n  }\n  ... on CodeVoucher {\n    code\n  }\n  giftCard {\n    lastFourDigits\n  }\n}\n\nfragment paymentAction on PaymentAction {\n  __typename\n  ... on FormPaymentAction {\n    html\n    formFields\n    formType\n  }\n  ... on RedirectPaymentAction {\n    url\n  }\n  ... on JavascriptPaymentAction {\n    script\n    formFields\n  }\n  ... on SuccessPaymentAction {\n    order {\n      id\n    }\n  }\n}": typeof types.CheckoutFragmentDoc,
    "fragment item on Item {\n  id\n  name\n  sizeLocalization {\n    name\n    countries {\n      code\n    }\n  }\n}\n\nfragment bundle on Bundle {\n  type\n  priceType\n  minPrice {\n    formattedValue\n  }\n  maxPrice {\n    formattedValue\n  }\n  sections {\n    id\n    quantity\n    items {\n      id\n      name\n      uri\n      media {\n        altText\n        source {\n          url\n        }\n      }\n      price {\n        formattedValue\n        value\n        currency {\n          code\n        }\n      }\n      items {\n        ...item\n        stock {\n          available\n        }\n      }\n    }\n  }\n}\n\nfragment variantSwatch on DisplayItem {\n  swatch: attributes(keys: [\"variant_swatch\"]) {\n    __typename\n    ... on DynamicAttribute {\n      elements {\n        __typename\n        key\n        ... on AttributeStringElement {\n          value\n        }\n      }\n    }\n  }\n}\n\nfragment listProduct on DisplayItem {\n  id\n  uri\n  name\n  media {\n    altText\n    source(sizeName: \"1350x0\") {\n      url\n    }\n  }\n  productVariant {\n    name\n  }\n  ...variantSwatch\n  relatedDisplayItems(relationType: \"variant\") {\n    relation\n    displayItems {\n      uri\n      productVariant {\n        name\n      }\n      ...variantSwatch\n    }\n  }\n  price {\n    formattedValue\n  }\n  bundle {\n    type\n    priceType\n    minPrice {\n      formattedValue\n    }\n  }\n}": typeof types.ItemFragmentDoc,
    "fragment cart on Selection {\n  lines {\n    ...line\n  }\n  grandTotal {\n    currency {\n      prefix\n      suffix\n    }\n  }\n}\n\nfragment line on Line {\n  __typename\n  id\n  item {\n    ...item\n  }\n  quantity\n  lineValue {\n    formattedValue\n    value\n  }\n  displayItem {\n    name\n    uri\n    media {\n      altText\n      source(sizeName: \"mini\") {\n        url\n      }\n    }\n  }\n  ... on BundleLine {\n    bundle {\n      type\n      sections {\n        quantity\n        lines {\n          id\n          lineValue {\n            formattedValue\n          }\n          name\n          quantity\n          item {\n            ...item\n          }\n        }\n      }\n    }\n  }\n}": typeof types.CartFragmentDoc,
    "fragment session on Session {\n  country {\n    code\n  }\n  countryState {\n    code\n  }\n  language {\n    code\n  }\n  market {\n    id\n  }\n  pricelist {\n    id\n  }\n  loggedIn {\n    id\n  }\n}": typeof types.SessionFragmentDoc,
};
const documents: Documents = {
    "\n      query receipt {\n        order {\n          ...order\n        }\n      }\n    ": types.ReceiptDocument,
    "\n      mutation paymentResult($paymentMethodFields: Map!) {\n        paymentResult(paymentMethodFields: $paymentMethodFields) {\n          type\n          userErrors {\n            message\n            path\n          }\n        }\n      }\n    ": types.PaymentResultDocument,
    "\n        mutation changeLocale($country: String!, $language: String!) {\n          setCountryState(countryCode: $country) {\n            userErrors {\n              __typename\n              message\n              path\n            }\n          }\n          setLanguage(code: $language) {\n            session {\n              ...session\n            }\n          }\n        }\n      ": types.ChangeLocaleDocument,
    "\n            mutation addFlexibleBundleToCart($item: String!, $sections: [BundleSectionInput!]!, $quantity: Int = 1) {\n              addFlexibleBundle(item: $item, quantity: $quantity, sections: $sections) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...cart\n                }\n              }\n            }\n          ": types.AddFlexibleBundleToCartDocument,
    "\n            mutation addItem($item: String!, $quantity: Int = 1) {\n              addItem(item: $item, quantity: $quantity) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...cart\n                }\n              }\n            }\n          ": types.AddItemDocument,
    "\n            mutation updateLine($id: String!, $quantity: Int!) {\n              updateLine(lineId: $id, quantity: $quantity) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...cart\n                }\n              }\n            }\n          ": types.UpdateLineDocument,
    "\n        query cart {\n          selection {\n            ...cart\n          }\n        }\n      ": types.CartDocument,
    "\n            mutation setAddress($billingAddress: AddressInput!, $shippingAddress: AddressInput!) {\n              setAddress(separateBillingAddress: $billingAddress, shippingAddress: $shippingAddress) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  __typename\n                  message\n                  path\n                }\n              }\n            }\n          ": types.SetAddressDocument,
    "\n            mutation setShippingMethod($id: Int!) {\n              setShippingMethod(id: $id) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": types.SetShippingMethodDocument,
    "\n            mutation setPaymentMethod($paymentMethod: Int!) {\n              setPaymentMethod(id: $paymentMethod) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": types.SetPaymentMethodDocument,
    "\n            mutation paymentInstructions($input: PaymentInstructionsInput!) {\n              paymentInstructions(input: $input) {\n                action {\n                  ...paymentAction\n                }\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  __typename\n                  message\n                  path\n                }\n              }\n            }\n          ": types.PaymentInstructionsDocument,
    "\n            mutation widgetEvent($payload: Map!) {\n              handleWidgetEvent(payload: $payload) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": types.WidgetEventDocument,
    "\n            mutation addVoucher($code: String!) {\n              addVoucher(code: $code) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": types.AddVoucherDocument,
    "\n            mutation removeVoucher($code: String!) {\n              removeVoucher(code: $code) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": types.RemoveVoucherDocument,
    "\n            mutation setCountryState($countryCode: String!, $stateCode: String!) {\n              setCountryState(countryCode: $countryCode, stateCode: $stateCode) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  __typename\n                  message\n                  path\n                }\n              }\n            }\n          ": types.SetCountryStateDocument,
    "\n            mutation updateLineCheckout($id: String!, $quantity: Int!) {\n              updateLine(lineId: $id, quantity: $quantity) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...checkout\n                }\n              }\n            }\n          ": types.UpdateLineCheckoutDocument,
    "\n            mutation applyGiftCard($cardNumber: String!, $pin: String) {\n              applyGiftCard(input: { cardNumber: $cardNumber, pin: $pin }) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          ": types.ApplyGiftCardDocument,
    "\n        query checkout {\n          selection {\n            ...checkout\n          }\n        }\n      ": types.CheckoutDocument,
    "\n      query session {\n        session {\n          ...session\n        }\n      }\n    ": types.SessionDocument,
    "\n      mutation setCountryAndLanguage($country: String!, $state: String, $language: String!) {\n        setCountryState(countryCode: $country, stateCode: $state) {\n          userErrors {\n            __typename\n            message\n            path\n          }\n        }\n        setLanguage(code: $language) {\n          session {\n            ...session\n          }\n        }\n      }\n    ": types.SetCountryAndLanguageDocument,
    "\n      query orders($limit: Int!, $page: Int!) {\n        customer {\n          orders(limit: $limit, page: $page) {\n            ...order\n          }\n          totalOrders\n        }\n      }\n    ": types.OrdersDocument,
    "\n      query relatedProducts($id: Int!, $language: String!, $market: Int!, $pricelist: Int!) {\n        displayItem(id: $id, languageCode: [$language], market: [$market], pricelist: [$pricelist]) {\n          relatedDisplayItems(relationType: \"standard\") {\n            relation\n            displayItems {\n              ...listProduct\n            }\n          }\n        }\n      }\n    ": types.RelatedProductsDocument,
    "\n        mutation login($email: String!, $password: String!) {\n          login(email: $email, password: $password) {\n            session {\n              ...session\n            }\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": types.LoginDocument,
    "\n        mutation register($input: CustomerRegisterInput!) {\n          registerCustomer(input: $input) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": types.RegisterDocument,
    "\n        mutation logout {\n          logout {\n            session {\n              ...session\n            }\n          }\n        }\n      ": types.LogoutDocument,
    "\n        mutation forgotPassword($email: String!, $uri: String!) {\n          requestPasswordResetEmail(email: $email, resetPasswordExternalUrl: $uri) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": types.ForgotPasswordDocument,
    "\n        mutation resetPassword($password: String!, $confirmPassword: String!, $i: String!, $id: String!) {\n          resetPassword(password: $password, confirmPassword: $confirmPassword, i: $i, id: $id) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      ": types.ResetPasswordDocument,
    "\n      mutation lookupProduct($uri: String!, $language: String!, $market: Int!, $pricelist: Int!) {\n        lookupUri(\n          uri: $uri\n          for: [DISPLAY_ITEM]\n          languageCode: [$language]\n          market: [$market]\n          pricelist: [$pricelist]\n        ) {\n          __typename\n          ... on DisplayItemUriLookupPayload {\n            displayItem {\n              id\n              available\n              uri\n              name\n              metaTitle\n              metaDescription\n              description {\n                formatted\n              }\n              media {\n                id\n                altText\n                source(sizeName: \"1350x0\") {\n                  url\n                }\n              }\n              price {\n                formattedValue\n                value\n                currency {\n                  code\n                }\n              }\n              items {\n                ...item\n                stock {\n                  available\n                  quantity\n                }\n              }\n              relatedDisplayItems(relationType: \"variant\") {\n                relation\n                displayItems {\n                  uri\n                  productVariant {\n                    name\n                  }\n                  ...variantSwatch\n                }\n              }\n              productVariant {\n                name\n              }\n              ...variantSwatch\n              translations {\n                language {\n                  code\n                }\n                uri\n              }\n              bundle {\n                ...bundle\n              }\n            }\n          }\n        }\n      }\n    ": types.LookupProductDocument,
    "\n      query products(\n        $page: Int!\n        $search: String\n        $sort: [CustomSortInput!] = []\n        $filters: [FilterInput!] = []\n        $limit: Int = 40\n        $market: Int!\n        $pricelist: Int!\n        $language: String!\n        $withFilters: Boolean = true\n      ) {\n        displayItems(\n          limit: $limit\n          page: $page\n          where: { search: $search, filters: $filters }\n          sort: $sort\n          market: [$market]\n          pricelist: [$pricelist]\n          languageCode: [$language]\n        ) {\n          list {\n            ...listProduct\n          }\n          pagination {\n            currentPage\n            lastPage\n          }\n          filters @include(if: $withFilters) {\n            key\n            anyAvailable\n            selectedValues\n            values {\n              __typename\n              value\n              filterCount\n              ... on BrandFilterValue {\n                name\n              }\n            }\n          }\n        }\n      }\n    ": types.ProductsDocument,
    "\n      query countries {\n        countries(onlyShipTo: true) {\n          name\n          code\n          states {\n            name\n            code\n          }\n          defaultLanguage {\n            code\n            languageCode\n          }\n          translations {\n            language {\n              code\n            }\n            name\n          }\n        }\n      }\n    ": types.CountriesDocument,
    "\n      query languages {\n        languages {\n          languageCode\n          name\n          code\n          countryCode\n        }\n      }\n    ": types.LanguagesDocument,
    "\n      query categories($limit: Int!, $language: String!, $market: Int!) {\n        categories(limit: $limit, parent: 0, languageCode: [$language], market: [$market]) {\n          list {\n            name\n            uri\n          }\n        }\n      }\n    ": types.CategoriesDocument,
    "\n      mutation lookupCategory($uri: String!, $language: String!, $market: Int!) {\n        lookupUri(uri: $uri, for: [CATEGORY], languageCode: [$language], market: [$market]) {\n          __typename\n          ... on CategoryUriLookupPayload {\n            category {\n              id\n              uri\n              name\n              metaTitle\n              metaDescription\n              childCategories {\n                name\n                uri\n              }\n              translations {\n                uri\n                language {\n                  code\n                }\n              }\n            }\n          }\n        }\n      }\n    ": types.LookupCategoryDocument,
    "fragment checkout on Selection {\n  lines {\n    ...line\n  }\n  grandTotal {\n    value\n    currency {\n      denominator\n      code\n    }\n  }\n  discounts {\n    ...voucher\n  }\n  externalGiftCardAvailable\n  checkout {\n    checkoutScript\n    separateBillingAddress {\n      ...address\n    }\n    shippingAddress {\n      ...address\n    }\n    paymentMethods {\n      id\n      uri\n      name\n      kind\n      initiateOnlySupported\n      handlingCost {\n        formattedValue\n        value\n      }\n    }\n    paymentMethod {\n      id\n    }\n    shippingMethods {\n      id\n      name\n      comment\n      price {\n        formattedValue\n        value\n      }\n    }\n    shippingMethod {\n      id\n      name\n      comment\n      price {\n        value\n        formattedValue\n      }\n    }\n    totals {\n      type\n      price {\n        value\n        formattedValue\n      }\n    }\n    widgets {\n      __typename\n      ... on IngridWidget {\n        snippet\n        deliveryOptionsAvailable\n      }\n      ... on KlarnaPaymentWidget {\n        client_token\n        authorizePayload\n      }\n    }\n  }\n}\n\nfragment address on Address {\n  country {\n    code\n    name\n  }\n  state {\n    code\n    name\n  }\n  address1\n  address2\n  city\n  zipCode\n  email\n  firstName\n  lastName\n  phoneNumber\n  companyName\n  vatNumber\n}\n\nfragment order on Order {\n  id\n  number\n  orderDate\n  status\n  totals {\n    type\n    price {\n      value\n      formattedValue\n    }\n  }\n  shippingAddress {\n    ...address\n  }\n  billingAddress {\n    ...address\n  }\n  shippingMethod {\n    id\n    name\n    comment\n    selected\n    price {\n      value\n      formattedValue\n    }\n  }\n  lines {\n    ...line\n  }\n}\n\nfragment voucher on Voucher {\n  name\n  value {\n    value\n    formattedValue\n  }\n  ... on CodeVoucher {\n    code\n  }\n  giftCard {\n    lastFourDigits\n  }\n}\n\nfragment paymentAction on PaymentAction {\n  __typename\n  ... on FormPaymentAction {\n    html\n    formFields\n    formType\n  }\n  ... on RedirectPaymentAction {\n    url\n  }\n  ... on JavascriptPaymentAction {\n    script\n    formFields\n  }\n  ... on SuccessPaymentAction {\n    order {\n      id\n    }\n  }\n}": types.CheckoutFragmentDoc,
    "fragment item on Item {\n  id\n  name\n  sizeLocalization {\n    name\n    countries {\n      code\n    }\n  }\n}\n\nfragment bundle on Bundle {\n  type\n  priceType\n  minPrice {\n    formattedValue\n  }\n  maxPrice {\n    formattedValue\n  }\n  sections {\n    id\n    quantity\n    items {\n      id\n      name\n      uri\n      media {\n        altText\n        source {\n          url\n        }\n      }\n      price {\n        formattedValue\n        value\n        currency {\n          code\n        }\n      }\n      items {\n        ...item\n        stock {\n          available\n        }\n      }\n    }\n  }\n}\n\nfragment variantSwatch on DisplayItem {\n  swatch: attributes(keys: [\"variant_swatch\"]) {\n    __typename\n    ... on DynamicAttribute {\n      elements {\n        __typename\n        key\n        ... on AttributeStringElement {\n          value\n        }\n      }\n    }\n  }\n}\n\nfragment listProduct on DisplayItem {\n  id\n  uri\n  name\n  media {\n    altText\n    source(sizeName: \"1350x0\") {\n      url\n    }\n  }\n  productVariant {\n    name\n  }\n  ...variantSwatch\n  relatedDisplayItems(relationType: \"variant\") {\n    relation\n    displayItems {\n      uri\n      productVariant {\n        name\n      }\n      ...variantSwatch\n    }\n  }\n  price {\n    formattedValue\n  }\n  bundle {\n    type\n    priceType\n    minPrice {\n      formattedValue\n    }\n  }\n}": types.ItemFragmentDoc,
    "fragment cart on Selection {\n  lines {\n    ...line\n  }\n  grandTotal {\n    currency {\n      prefix\n      suffix\n    }\n  }\n}\n\nfragment line on Line {\n  __typename\n  id\n  item {\n    ...item\n  }\n  quantity\n  lineValue {\n    formattedValue\n    value\n  }\n  displayItem {\n    name\n    uri\n    media {\n      altText\n      source(sizeName: \"mini\") {\n        url\n      }\n    }\n  }\n  ... on BundleLine {\n    bundle {\n      type\n      sections {\n        quantity\n        lines {\n          id\n          lineValue {\n            formattedValue\n          }\n          name\n          quantity\n          item {\n            ...item\n          }\n        }\n      }\n    }\n  }\n}": types.CartFragmentDoc,
    "fragment session on Session {\n  country {\n    code\n  }\n  countryState {\n    code\n  }\n  language {\n    code\n  }\n  market {\n    id\n  }\n  pricelist {\n    id\n  }\n  loggedIn {\n    id\n  }\n}": types.SessionFragmentDoc,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query receipt {\n        order {\n          ...order\n        }\n      }\n    "): typeof import('./graphql').ReceiptDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      mutation paymentResult($paymentMethodFields: Map!) {\n        paymentResult(paymentMethodFields: $paymentMethodFields) {\n          type\n          userErrors {\n            message\n            path\n          }\n        }\n      }\n    "): typeof import('./graphql').PaymentResultDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation changeLocale($country: String!, $language: String!) {\n          setCountryState(countryCode: $country) {\n            userErrors {\n              __typename\n              message\n              path\n            }\n          }\n          setLanguage(code: $language) {\n            session {\n              ...session\n            }\n          }\n        }\n      "): typeof import('./graphql').ChangeLocaleDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation addFlexibleBundleToCart($item: String!, $sections: [BundleSectionInput!]!, $quantity: Int = 1) {\n              addFlexibleBundle(item: $item, quantity: $quantity, sections: $sections) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...cart\n                }\n              }\n            }\n          "): typeof import('./graphql').AddFlexibleBundleToCartDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation addItem($item: String!, $quantity: Int = 1) {\n              addItem(item: $item, quantity: $quantity) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...cart\n                }\n              }\n            }\n          "): typeof import('./graphql').AddItemDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation updateLine($id: String!, $quantity: Int!) {\n              updateLine(lineId: $id, quantity: $quantity) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...cart\n                }\n              }\n            }\n          "): typeof import('./graphql').UpdateLineDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query cart {\n          selection {\n            ...cart\n          }\n        }\n      "): typeof import('./graphql').CartDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation setAddress($billingAddress: AddressInput!, $shippingAddress: AddressInput!) {\n              setAddress(separateBillingAddress: $billingAddress, shippingAddress: $shippingAddress) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  __typename\n                  message\n                  path\n                }\n              }\n            }\n          "): typeof import('./graphql').SetAddressDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation setShippingMethod($id: Int!) {\n              setShippingMethod(id: $id) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          "): typeof import('./graphql').SetShippingMethodDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation setPaymentMethod($paymentMethod: Int!) {\n              setPaymentMethod(id: $paymentMethod) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          "): typeof import('./graphql').SetPaymentMethodDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation paymentInstructions($input: PaymentInstructionsInput!) {\n              paymentInstructions(input: $input) {\n                action {\n                  ...paymentAction\n                }\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  __typename\n                  message\n                  path\n                }\n              }\n            }\n          "): typeof import('./graphql').PaymentInstructionsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation widgetEvent($payload: Map!) {\n              handleWidgetEvent(payload: $payload) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          "): typeof import('./graphql').WidgetEventDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation addVoucher($code: String!) {\n              addVoucher(code: $code) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          "): typeof import('./graphql').AddVoucherDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation removeVoucher($code: String!) {\n              removeVoucher(code: $code) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          "): typeof import('./graphql').RemoveVoucherDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation setCountryState($countryCode: String!, $stateCode: String!) {\n              setCountryState(countryCode: $countryCode, stateCode: $stateCode) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  __typename\n                  message\n                  path\n                }\n              }\n            }\n          "): typeof import('./graphql').SetCountryStateDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation updateLineCheckout($id: String!, $quantity: Int!) {\n              updateLine(lineId: $id, quantity: $quantity) {\n                userErrors {\n                  message\n                  path\n                }\n                selection {\n                  ...checkout\n                }\n              }\n            }\n          "): typeof import('./graphql').UpdateLineCheckoutDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation applyGiftCard($cardNumber: String!, $pin: String) {\n              applyGiftCard(input: { cardNumber: $cardNumber, pin: $pin }) {\n                selection {\n                  ...checkout\n                }\n                userErrors {\n                  message\n                  path\n                }\n              }\n            }\n          "): typeof import('./graphql').ApplyGiftCardDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query checkout {\n          selection {\n            ...checkout\n          }\n        }\n      "): typeof import('./graphql').CheckoutDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query session {\n        session {\n          ...session\n        }\n      }\n    "): typeof import('./graphql').SessionDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      mutation setCountryAndLanguage($country: String!, $state: String, $language: String!) {\n        setCountryState(countryCode: $country, stateCode: $state) {\n          userErrors {\n            __typename\n            message\n            path\n          }\n        }\n        setLanguage(code: $language) {\n          session {\n            ...session\n          }\n        }\n      }\n    "): typeof import('./graphql').SetCountryAndLanguageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query orders($limit: Int!, $page: Int!) {\n        customer {\n          orders(limit: $limit, page: $page) {\n            ...order\n          }\n          totalOrders\n        }\n      }\n    "): typeof import('./graphql').OrdersDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query relatedProducts($id: Int!, $language: String!, $market: Int!, $pricelist: Int!) {\n        displayItem(id: $id, languageCode: [$language], market: [$market], pricelist: [$pricelist]) {\n          relatedDisplayItems(relationType: \"standard\") {\n            relation\n            displayItems {\n              ...listProduct\n            }\n          }\n        }\n      }\n    "): typeof import('./graphql').RelatedProductsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation login($email: String!, $password: String!) {\n          login(email: $email, password: $password) {\n            session {\n              ...session\n            }\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      "): typeof import('./graphql').LoginDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation register($input: CustomerRegisterInput!) {\n          registerCustomer(input: $input) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      "): typeof import('./graphql').RegisterDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation logout {\n          logout {\n            session {\n              ...session\n            }\n          }\n        }\n      "): typeof import('./graphql').LogoutDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation forgotPassword($email: String!, $uri: String!) {\n          requestPasswordResetEmail(email: $email, resetPasswordExternalUrl: $uri) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      "): typeof import('./graphql').ForgotPasswordDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        mutation resetPassword($password: String!, $confirmPassword: String!, $i: String!, $id: String!) {\n          resetPassword(password: $password, confirmPassword: $confirmPassword, i: $i, id: $id) {\n            userErrors {\n              message\n              path\n            }\n          }\n        }\n      "): typeof import('./graphql').ResetPasswordDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      mutation lookupProduct($uri: String!, $language: String!, $market: Int!, $pricelist: Int!) {\n        lookupUri(\n          uri: $uri\n          for: [DISPLAY_ITEM]\n          languageCode: [$language]\n          market: [$market]\n          pricelist: [$pricelist]\n        ) {\n          __typename\n          ... on DisplayItemUriLookupPayload {\n            displayItem {\n              id\n              available\n              uri\n              name\n              metaTitle\n              metaDescription\n              description {\n                formatted\n              }\n              media {\n                id\n                altText\n                source(sizeName: \"1350x0\") {\n                  url\n                }\n              }\n              price {\n                formattedValue\n                value\n                currency {\n                  code\n                }\n              }\n              items {\n                ...item\n                stock {\n                  available\n                  quantity\n                }\n              }\n              relatedDisplayItems(relationType: \"variant\") {\n                relation\n                displayItems {\n                  uri\n                  productVariant {\n                    name\n                  }\n                  ...variantSwatch\n                }\n              }\n              productVariant {\n                name\n              }\n              ...variantSwatch\n              translations {\n                language {\n                  code\n                }\n                uri\n              }\n              bundle {\n                ...bundle\n              }\n            }\n          }\n        }\n      }\n    "): typeof import('./graphql').LookupProductDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query products(\n        $page: Int!\n        $search: String\n        $sort: [CustomSortInput!] = []\n        $filters: [FilterInput!] = []\n        $limit: Int = 40\n        $market: Int!\n        $pricelist: Int!\n        $language: String!\n        $withFilters: Boolean = true\n      ) {\n        displayItems(\n          limit: $limit\n          page: $page\n          where: { search: $search, filters: $filters }\n          sort: $sort\n          market: [$market]\n          pricelist: [$pricelist]\n          languageCode: [$language]\n        ) {\n          list {\n            ...listProduct\n          }\n          pagination {\n            currentPage\n            lastPage\n          }\n          filters @include(if: $withFilters) {\n            key\n            anyAvailable\n            selectedValues\n            values {\n              __typename\n              value\n              filterCount\n              ... on BrandFilterValue {\n                name\n              }\n            }\n          }\n        }\n      }\n    "): typeof import('./graphql').ProductsDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query countries {\n        countries(onlyShipTo: true) {\n          name\n          code\n          states {\n            name\n            code\n          }\n          defaultLanguage {\n            code\n            languageCode\n          }\n          translations {\n            language {\n              code\n            }\n            name\n          }\n        }\n      }\n    "): typeof import('./graphql').CountriesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query languages {\n        languages {\n          languageCode\n          name\n          code\n          countryCode\n        }\n      }\n    "): typeof import('./graphql').LanguagesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query categories($limit: Int!, $language: String!, $market: Int!) {\n        categories(limit: $limit, parent: 0, languageCode: [$language], market: [$market]) {\n          list {\n            name\n            uri\n          }\n        }\n      }\n    "): typeof import('./graphql').CategoriesDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      mutation lookupCategory($uri: String!, $language: String!, $market: Int!) {\n        lookupUri(uri: $uri, for: [CATEGORY], languageCode: [$language], market: [$market]) {\n          __typename\n          ... on CategoryUriLookupPayload {\n            category {\n              id\n              uri\n              name\n              metaTitle\n              metaDescription\n              childCategories {\n                name\n                uri\n              }\n              translations {\n                uri\n                language {\n                  code\n                }\n              }\n            }\n          }\n        }\n      }\n    "): typeof import('./graphql').LookupCategoryDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment checkout on Selection {\n  lines {\n    ...line\n  }\n  grandTotal {\n    value\n    currency {\n      denominator\n      code\n    }\n  }\n  discounts {\n    ...voucher\n  }\n  externalGiftCardAvailable\n  checkout {\n    checkoutScript\n    separateBillingAddress {\n      ...address\n    }\n    shippingAddress {\n      ...address\n    }\n    paymentMethods {\n      id\n      uri\n      name\n      kind\n      initiateOnlySupported\n      handlingCost {\n        formattedValue\n        value\n      }\n    }\n    paymentMethod {\n      id\n    }\n    shippingMethods {\n      id\n      name\n      comment\n      price {\n        formattedValue\n        value\n      }\n    }\n    shippingMethod {\n      id\n      name\n      comment\n      price {\n        value\n        formattedValue\n      }\n    }\n    totals {\n      type\n      price {\n        value\n        formattedValue\n      }\n    }\n    widgets {\n      __typename\n      ... on IngridWidget {\n        snippet\n        deliveryOptionsAvailable\n      }\n      ... on KlarnaPaymentWidget {\n        client_token\n        authorizePayload\n      }\n    }\n  }\n}\n\nfragment address on Address {\n  country {\n    code\n    name\n  }\n  state {\n    code\n    name\n  }\n  address1\n  address2\n  city\n  zipCode\n  email\n  firstName\n  lastName\n  phoneNumber\n  companyName\n  vatNumber\n}\n\nfragment order on Order {\n  id\n  number\n  orderDate\n  status\n  totals {\n    type\n    price {\n      value\n      formattedValue\n    }\n  }\n  shippingAddress {\n    ...address\n  }\n  billingAddress {\n    ...address\n  }\n  shippingMethod {\n    id\n    name\n    comment\n    selected\n    price {\n      value\n      formattedValue\n    }\n  }\n  lines {\n    ...line\n  }\n}\n\nfragment voucher on Voucher {\n  name\n  value {\n    value\n    formattedValue\n  }\n  ... on CodeVoucher {\n    code\n  }\n  giftCard {\n    lastFourDigits\n  }\n}\n\nfragment paymentAction on PaymentAction {\n  __typename\n  ... on FormPaymentAction {\n    html\n    formFields\n    formType\n  }\n  ... on RedirectPaymentAction {\n    url\n  }\n  ... on JavascriptPaymentAction {\n    script\n    formFields\n  }\n  ... on SuccessPaymentAction {\n    order {\n      id\n    }\n  }\n}"): typeof import('./graphql').CheckoutFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment item on Item {\n  id\n  name\n  sizeLocalization {\n    name\n    countries {\n      code\n    }\n  }\n}\n\nfragment bundle on Bundle {\n  type\n  priceType\n  minPrice {\n    formattedValue\n  }\n  maxPrice {\n    formattedValue\n  }\n  sections {\n    id\n    quantity\n    items {\n      id\n      name\n      uri\n      media {\n        altText\n        source {\n          url\n        }\n      }\n      price {\n        formattedValue\n        value\n        currency {\n          code\n        }\n      }\n      items {\n        ...item\n        stock {\n          available\n        }\n      }\n    }\n  }\n}\n\nfragment variantSwatch on DisplayItem {\n  swatch: attributes(keys: [\"variant_swatch\"]) {\n    __typename\n    ... on DynamicAttribute {\n      elements {\n        __typename\n        key\n        ... on AttributeStringElement {\n          value\n        }\n      }\n    }\n  }\n}\n\nfragment listProduct on DisplayItem {\n  id\n  uri\n  name\n  media {\n    altText\n    source(sizeName: \"1350x0\") {\n      url\n    }\n  }\n  productVariant {\n    name\n  }\n  ...variantSwatch\n  relatedDisplayItems(relationType: \"variant\") {\n    relation\n    displayItems {\n      uri\n      productVariant {\n        name\n      }\n      ...variantSwatch\n    }\n  }\n  price {\n    formattedValue\n  }\n  bundle {\n    type\n    priceType\n    minPrice {\n      formattedValue\n    }\n  }\n}"): typeof import('./graphql').ItemFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment cart on Selection {\n  lines {\n    ...line\n  }\n  grandTotal {\n    currency {\n      prefix\n      suffix\n    }\n  }\n}\n\nfragment line on Line {\n  __typename\n  id\n  item {\n    ...item\n  }\n  quantity\n  lineValue {\n    formattedValue\n    value\n  }\n  displayItem {\n    name\n    uri\n    media {\n      altText\n      source(sizeName: \"mini\") {\n        url\n      }\n    }\n  }\n  ... on BundleLine {\n    bundle {\n      type\n      sections {\n        quantity\n        lines {\n          id\n          lineValue {\n            formattedValue\n          }\n          name\n          quantity\n          item {\n            ...item\n          }\n        }\n      }\n    }\n  }\n}"): typeof import('./graphql').CartFragmentDoc;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment session on Session {\n  country {\n    code\n  }\n  countryState {\n    code\n  }\n  language {\n    code\n  }\n  market {\n    id\n  }\n  pricelist {\n    id\n  }\n  loggedIn {\n    id\n  }\n}"): typeof import('./graphql').SessionFragmentDoc;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
